name: Atlas Carpet
description: 
url:
baseurl: ""
permalink: /:title/
favicon: /assets/img/favicon.ico
social_image: /assets/img/social-image.png
google_analytics:
  id:
kramdown:
  input: GFM
sass:
  sass_dir: assets/partials
  style: compressed
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME